version: 2
updates:
  # Updates for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Updates for ruby gems
  - package-ecosystem: "bundler"
    directory: "/src/dokumentvwsys"
    schedule:
      interval: "daily"
  # Updates for javascript
  - package-ecosystem: "javascript"
    directory: "/src/dokumentvwsys"
    schedule:
      interval: "daily"
