version: "3.8"

services:
  database:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - ./dokumentvwsys:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  db_data:
